zero: synapse: auto-stop Synapse when updating config
Change-Id: I253ab8860c63d401ba7dbd681ff43939a0c9891e

diff --git a/synapse/synapse-update b/synapse/synapse-update
--- a/synapse/synapse-update
+++ b/synapse/synapse-update
@@ -7,10 +7,21 @@
 source=/system/res/synapse
 target=/res/synapse
 
-if [ "$1" != "--no-confirm" ]; then
-	echo ""
-	echo "MAKE SURE SYNAPSE IS CLOSED BEFORE YOU CONTINUE!!! - PRESS ENTER TO CONTINUE!!!"
-	read
+#
+# Force-stop Synapse application
+#
+if [ "$1" != "--no-force-stop" ]; then
+	echo -n "[*] Force-stopping Synapse application..."
+
+	am force-stop com.af.synapse
+	rc=$?
+
+	if [ $rc != 0 ]; then
+		echo " Failed..."
+		exit 1
+	fi
+
+	echo " Done!"
 fi
 
 #
